const actionsTypes = {
    ADICIONAR_ANUNCIO: 'ADICIONAR_ANUNCIO',
    REMOVER_ANUNCIO: 'REMOVER_ANUNCIO',
    ANUNCIO_SELECIONADO: 'ANUNCIO_SELECIONADO',
    LISTAR_ANUNCIOS: 'LISTAR_ANUNCIOS',
    EDITAR_ANUNCIO: 'EDITAR_ANUNCIO',
    ATUALIZAR_ANUNCIO: 'ATUALIZAR_ANUNCIO',
};

export { actionsTypes };