const actionsTypes = {
    ADICIONAR_ANUNCIO: 'ADICIONAR_ANUNCIO',
    REMOVER_ANUNCIO: 'REMOVER_ANUNCIO',
    ANUNCIO_SELECIONADO: 'ANUNCIO_SELECIONADO',
    LISTAR_ANUNCIOS: 'LISTAR_ANUNCIOS',
};

export { actionsTypes };